# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 CERN.
#
# CERN Analysis Preservation is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

version: '2.3'
services:
  # Load balancer
  lb:
    extends:
      file: docker-services.yml
      service: lb
    links:
      - frontend
  # Frontend
  frontend:
    extends:
      file: docker-services.yml
      service: frontend
    volumes:
      - static_data:/opt/cap/var/instance/static
      - ./ui/dist:/html
    links:
      # - web-ui
      - web-api
  # UI Application
  # web-ui:
  #   build: ./ui
  #   image: cap/ui
  #   volumes:
  #     - './ui:/usr/src/app'
  #     - '/usr/src/app/node_modules'
  #   ports:
  #     - "3000:3000"
  #   image: cap-web-ui
  # API Rest Application
  web-api:
    extends:
      file: docker-services.yml
      service: app
    command: uwsgi /opt/cap/var/instance/uwsgi_rest.ini
    image: cap-web-api
    ports:
      - "5000"
    volumes:
      - static_data:/opt/cap/var/instance/static
    links:
      - cache
      - es
      - mq
      - db
  # Worker
  worker:
    extends:
      file: docker-services.yml
      service: app
    restart: "always"
    command: "celery worker -A cap.celery --loglevel=INFO"
    image: cap-worker
    links:
      - cache
      - es
      - mq
      - db
  # Monitoring
  flower:
    extends:
      file: docker-services.yml
      service: flower
    links:
      - mq
  # Base services
  cache:
    extends:
      file: docker-services.yml
      service: cache
  db:
    extends:
      file: docker-services.yml
      service: db
  mq:
    extends:
      file: docker-services.yml
      service: mq
  es:
    extends:
      file: docker-services.yml
      service: es
volumes:
  static_data:
